### ISSUE TITLE
Requesting an update to Python 3.6

### ISSUE THREAD

**Issue by rhaskett** [conda-forge/pykalman-feedstock#2]
This is the most commonly used conda for grabbing PyKalman.  Just a quick request for a rebuild including 3.6 as I'm not sufficiently knowledgeable to do it myself.

**Comment by pmlandwehr** [comment]
I'm building  new `noarch` version, and will merge when it's done. That should hopefully take care of things!

**Comment by jakirkham** [comment]
The `noarch` package is now available. Going to close this out as resolved.

**Comment by rhaskett** [comment]
thanks
